import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/Header";
import {ThemeProvider} from "@/components/ThemeProvider";
import ClientProviders from "@/components/ClientProviders";
import React from "react";
import FirebaseAuthProvider from "@/components/FirebaseAuthProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientProviders>
        <html lang="en">
          <body className="flex flex-col min-h-screen">
          <FirebaseAuthProvider>
              <ThemeProvider
                  attribute="class"
                  defaultTheme="system"
                  enableSystem
                  disableTransitionOnChange
              >
                  <Header />
                  {children}
              </ThemeProvider>
          </FirebaseAuthProvider>
          </body>
        </html>
    </ClientProviders>
  );
}
